### PR TITLE
Fix content bookmarking in Firefox, #47

### PR DESCRIPTION
**Pull request by MikkCZ**
I have rewritten the bookmarking context menu action as suggested in #47. Unfortunately there is [bug 1344465](https://bugzilla.mozilla.org/show_bug.cgi?id=1344465), which breaks it with Firefox e10s (it works in non-e10s windows).

### CODE REVIEW

**Comment by MikkCZ** [comment]
But it seems we can actually use XHR POST for submitting the data and than just open a new tab with https://theoldreader.com/bookmarks/new.

**Comment by kav2k** [comment]
Thanks. I'll try to test it today, and merge it before further refactoring is done.

**Comment by kav2k** [comment]
There's a tiny problem, not sure if it can be worked around though.
Firefox's security model prevents "Cancel" from working on the newly opened page.

**Comment by MikkCZ** [comment]
Good catch. But is Firefox security? When I click the Cancel button, I see `TypeError: s.attr(...) is undefined` in the console. That looks more like a bug in the JavaScript of the page.

**Comment by MikkCZ** [comment]
But even if it works, the button click should close the tab using `window.close()`, which is not possible for windows, that were not opened with JS. Alternatively we can add a content script for this page, that would add its own listener using [`tabs.remove()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/remove).

**Comment by kav2k** [comment]
It shows an explicit security error for `window.close()`.

I'm all for making it a content script capability. This should be specific enough to find the button, but gotta check if it exists at script injection.

    document.querySelector(".bookmark-btns > a[href='javascript:window.close();']")

Also should check if the content script is allowed to simply call `window.close()` here - that would avoid adding another `onMessage` branch.

**Comment by MikkCZ** [comment]
No. :( `window.close()` cannot be called from the content script context. But using the messaging, the change is not that big.

**Comment by kav2k** [comment]
Thanks for this!

**Pull request merged**
