### PR TITLE
Use default color scheme for the badge, current scheme (black on dark red) is hard to read

### PR DESCRIPTION
**Pull request by vincentjacobs**
Remove custom background color to increase badge legibility

### CODE REVIEW

**Comment by kav2k** [comment]
Disagree with this solution.

Instead, Firefox detection should be performed and [`setBadgeTextColor`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeTextColor) used to set text color as white, as is the behavior in Chrome.

**Comment by kav2k** [comment]
I agree that FF is a problem

But it should be looking like this instead: Chrome

**Comment by vincentjacobs** [comment]
This solution actually _does_ result in the desired behavior described by @kav2k. Both background color AND text color change, to bright red and white respectively. This could be because this is the (hard-coded) default styling for Firefox, or because the brighter red background results in a different contrasting text color, I don't know. 

Actual screenshot from running the modified extension:

Screenshot 2021-01-21 at 10 05 11

**Comment by kav2k** [comment]
I see. So we're hitting an edge case where contrast decision disagrees between FF and Chrome - because of the brighter red.

However, removing the custom color would produce undesirable results in Chrome: image

So I still stand by consistency: have the badge color and if `browser.browserAction.setBadgeTextColor` exists use it to set the text color to pure white.

**Comment by vincentjacobs** [comment]
Implemented as suggested

**Comment by kav2k** [comment]
Excellent, I'll take a look when I have time to merge but it looks good.

**Comment by kav2k** [comment]
The new version 1.5.3 with this integrated is up at AMO. Thanks again for the patch.

**Pull request merged**
